export default {
    SAVE: "Данные были успешно сохранены",
    DELETE: "Данные были успешно удалены",
    UPDATE: "Данные успешно изменены",
    RETRIEVE_DATA_ERROR: "Произошла ошибка при получении данных",
    RETRIEVE_DATA_SUCCESS: "Данные загружены успешно",
    CURRENT_CALLS: "Текущие звонки",
    NO_REGISTERED_CALLS: "Не зарегистрированные",
    ALL_CALLS: "Все звонки",
    REGISTRATE_APPLICATION: "Регистрация обращения",
    REFRESH: "Обновить",
    STATISTICS: "Статистика",
    FILTER: "ПОСМОТРЕТЬ",
    DAY_TODAY: "День (cегодня)",
    WEEK: "Неделя",
    MONTH: "Месяц",
    BY_CALL: "работа операторов",
    BY_WAIT: "результат",
    BY_TAXPAYERS: "обращения по статусу налогоплательщиков",
    BY_TERRITORY: "по регионам",
    BY_CATEGORY: "по категориям",
    STATE_WAIT: "Ожидания",
    STATE_BUSY: "Заняты",
    STATE_MISSED: "Пропущены",
    STATE_NOT_BUSY: "Свободные",
    STATE_ANSWERED: "Отвеченные",
    STATE_IRREGULARITY: "Неправильность",
    STATE_CALL_CENTER: "Введены",
    STATE_TRUST_PHONE: "Не введены",
    CALL_CENTER: "Call center",
    TRUST_PHONE: "Тел.доверия",
    STATE_SOCIAL_NETWORK: "Соц.сети",
    STATE_TOTAL: "Всего",
    EXIT: "Выход",
    ENTER: "Вход",
    CLIENT_CALL_HISTORY: "История звонков клиентов",
    NO_DATA_FOUND: "Информация не найдена",
    DOWNLOAD: "скачать",
    ROW_NUMBER: "№",
    ID: "ИД",
    DIRECTION: "направление",
    PHONE_NUMBER: "телефон номер",
    HOLD_TIME: "время ожидания",
    CALL_DURATION: "продолжительность разговора",
    CALL_CENTER_TYPE: "тип раздела",
    INFORMATION: "информация",
    REGISTRATION_DATE: "дата регистрации",
    TIN: "ИНН",
    APPLICANT_NAME: "имя заявителя",
    ADDRESS: "адрес",
    APPLICATION_DESCRIPTION: "содержание обращения",
    COMMENTARY: "комментарий",
    OPERATOR: "Оператор",
    OPERATOR_NAME: "Ф.И.О оператора",
    CALL_HISTORY_COUNT: "Кол-во звонков",
    CALL_HISTORY: "история звонков",
    OPERATOR_TYPE: "Тип",
    INFORMATIVE_APPLICATION: "информационное обращения",
    FORMING_APPLICATION: "оформить обращения",
    TAXPAYER_TYPE: "вид налогоплательщика",
    REGION: "область",
    DISTRICT: "район/город",
    EXTRA_PHONE_NUMBER: "дополнительный тел",
    MAIL: "почта",
    CATEGORY: "категория",
    SUB_CATEGORY: "под категория",
    THEME: "тема",
    RESPONSIVE_PERSON: "ответственный",
    APPLICATION_RESULT: "результат обращения",
    BUTTON_SAVE: "сохранить",
    BUTTON_CANCEL: "отменить",
    COUNT: "количество",
    PREVIOUS_MONTH: "пред-месяцев",
    PERCENT: "процент",
    TAXPAYERS: "Налогоплательщики",
    BACK_TO_REPUBLIC: "переход в республиканскую",
    BACK_TO_SUB_CATEGORY_LEVEL: "вернуться в подкатегорию",
    BACK_TO_CATEGORY_LEVEL: "вернуться в категорию",
    CALL_VOICE: "аудио",
    REPORTS: "отчеты",
    REPORT_DISTRIBUTE_QUESTIONS_BY_REGIONS: "распределение вопросов по регионам",
    REPORT_DISTRIBUTE_QUESTIONS_BY_CATEGORIES: "распределение вопросы по содержанию",
    REPORT_DISTRIBUTE_QUESTIONS_BY_TIN_TYPES: "распределение вопросы исходили из какой категории",
    MONTH_1: "январь",
    MONTH_2: "февраль",
    MONTH_3: "март",
    MONTH_4: "апрель",
    MONTH_5: "май",
    MONTH_6: "июнь",
    MONTH_7: "июль",
    MONTH_8: "август",
    MONTH_9: "сентябрь",
    MONTH_10: "октябрь",
    MONTH_11: "ноябрь",
    MONTH_12: "декабрь",
    QUARTER: "квартал",
    TAX_TYPE: "тип налога",
    APPLICANT_TYPE: "тип заявителя",
    PLACE_HOLDER_INPUT_PHONE_NUMBER: "введите номер телефона",
    PLACE_HOLDER_INPUT_TIN: "введите ИНН"
}