export default {
    SAVE: "Маълумотлар муваффақиятли сақланди",
    DELETE: "Маълумотлар ўчирилди",
    UPDATE: "Маълумотлар муваффақиятли ўзгартирилди",
    RETRIEVE_DATA_ERROR: "Маълумотларни қабул қилишда хатолик юз берди",
    RETRIEVE_DATA_SUCCESS: "Маълумотлар муваффақиятли юкланди",
    CURRENT_CALLS: "Жорий қўнғироқлар",
    NO_REGISTERED_CALLS: "Рўйхатдан ўтмаган",
    ALL_CALLS: "Барча қўнғироқлар",
    REGISTRATE_APPLICATION: "Мурожатчини рўйхатдан ўтказиш",
    REFRESH: "Янгилаш",
    STATISTICS: "Статистика",
    FILTER: "КЎРИШ",
    DAY_TODAY: "Кунлик (бугун)",
    WEEK: "Ҳафталик",
    MONTH: "Ойлик",
    BY_CALL: "операторлар иш жараёни",
    BY_WAIT: "натижалар",
    BY_TAXPAYERS: "солиқ тўловчилар бўйича мурожаатлар",
    BY_TERRITORY: "ҳудудлар бўйича",
    BY_CATEGORY: "тоифалар бўйича",
    STATE_WAIT: "Кутаётган",
    STATE_BUSY: "Банд",
    STATE_MISSED: "Ўтказиб.юб",
    STATE_NOT_BUSY: "Банд эмас",
    STATE_ANSWERED: "Жавоб берилган",
    STATE_IRREGULARITY: "Қоидабузарлик",
    STATE_CALL_CENTER: "Колл Маркази",
    STATE_TRUST_PHONE: "Ишонч.Тел",
    STATE_SOCIAL_NETWORK: "Ижтимоий.Тар",
    STATE_TOTAL: "Барчаси",
    EXIT: "Чиқиш",
    ENTER: "Кириш",
    CLIENT_CALL_HISTORY: "Мижоз қўнғироқлар тарихи",
    NO_DATA_FOUND: "Ҳеч қандай маълумот топилмади",
    DOWNLOAD: "юклаб олиш",
    ROW_NUMBER: "№",
    ID: "ID",
    DIRECTION: "йўналиш",
    PHONE_NUMBER: "телефон рақами",
    HOLD_TIME: "кутиш вақти",
    CALL_DURATION: "мулоқот давомийлиги",
    CALL_CENTER_TYPE: "бўлим тури",
    INFORMATION: "маълумот",
    REGISTRATION_DATE: "рўйҳатга олинган сана",
    TIN: "СТИР",
    APPLICANT_NAME: "мурожаатчи исми",
    ADDRESS: "манзил",
    APPLICATION_DESCRIPTION: "мурожаат мазмуни",
    COMMENTARY: "қисқа ёзув",
    OPERATOR: "Оператор",
    OPERATOR_NAME: "Оператор ФИО",
    CALL_HISTORY_COUNT: "Қўнғироқлар сони",
    CALL_HISTORY: "қўнғироқлар тарихи",
    OPERATOR_TYPE: "Тури",
    INFORMATIVE_APPLICATION: "информатив мурожаат",
    FORMING_APPLICATION: "мурожаатни тўлиқ шакллантириш",
    TAXPAYER_TYPE: "солиқ тўловчи тури",
    REGION: "вилоят",
    DISTRICT: "туман/шаҳар",
    EXTRA_PHONE_NUMBER: "қўшимча телефон",
    MAIL: "почта",
    CATEGORY: "тоифа",
    SUB_CATEGORY: "қуйи тоифа",
    THEME: "мавзу",
    RESPONSIVE_PERSON: "масъул шахс",
    APPLICATION_RESULT: "мурожаат натижаси",
    BUTTON_SAVE: "сақлаш",
    BUTTON_CANCEL: "бекор қилиш",
    COUNT: "сони",
    PREVIOUS_MONTH: "олдинги ой",
    PERCENT: "фоиз",
    TAXPAYERS: "Солиқ тўловчилар",
    BACK_TO_REPUBLIC: "республика кесимига ўтиш",
    BACK_TO_SUB_CATEGORY_LEVEL: "қуйи категорияга қайтиш",
    BACK_TO_CATEGORY_LEVEL: "категорияга қайтиш",
    CALL_VOICE: "овоз",
    REPORTS: "ҳисоботлар",
    REPORT_DISTRIBUTE_QUESTIONS_BY_REGIONS: "саволларни ҳудудлар бўйича бўлиниши",
    REPORT_DISTRIBUTE_QUESTIONS_BY_CATEGORIES: "саволларни мазмунига кўра бўлиниши",
    REPORT_DISTRIBUTE_QUESTIONS_BY_TIN_TYPES: "саволлар кайси тоифадан келиб тушган",
    MONTH_1: "январь",
    MONTH_2: "февраль",
    MONTH_3: "март",
    MONTH_4: "апрель",
    MONTH_5: "май",
    MONTH_6: "июнь",
    MONTH_7: "июль",
    MONTH_8: "август",
    MONTH_9: "сентябрь",
    MONTH_10: "октябрь",
    MONTH_11: "ноябрь",
    MONTH_12: "декабрь",
    QUARTER: "чорак",
    TAX_TYPE: "солиқ тури",
    APPLICANT_TYPE: "муроожатчи тури",
    PLACE_HOLDER_INPUT_PHONE_NUMBER: "телефон рақамини киритинг",
    PLACE_HOLDER_INPUT_TIN: "СТИР рақамини киритинг"
}